### ISSUE TITLE
Change text of buttons

### ISSUE THREAD

**Issue by hjJunior** [stephentuso/welcome-android#10]
Hey how I can change the text from buttons "done" and "skip" 
I not found method for do this, please help me

**Comment by stephentuso** [comment]
That is currently done through styles:

```xml
<style name="CustomWelcomeScreenTheme" parent="WelcomeScreenTheme">
    <item name="welcomeButtonSkipText">your string</item>
    <item name="welcomeButtonDoneText">your string</item>
</style>
```
Then, you would apply it by calling `.theme(R.style.CustomWelcomeScreenTheme)` on your builder
