### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by MateiRadu** [stephentuso/welcome-android#17]
I configured my WelcomeActivity following the read me guide but on execution my project crashes with the following message in Logcat:

> No field view_pager of type I in class com/stephentuso/welcome/R.id; or its superclasses

I'm using the Android Emulator (API 24) for testing.

Is this a known issue? If so, are there any workarounds?

**Comment by stephentuso** [comment]
Yes, this is most likely due to a naming conflict and will be fixed in version 1.0 (see #13). You probably have a layout resource in your app module called `activity_welcome.xml`

**Comment by MateiRadu** [comment]
Oh yes, that worked like a charm! :smiley:
Thank you @stephentuso

**Comment by stephentuso** [comment]
No problem
