### ISSUE TITLE
swipeToDismiss(true) does not work in RTL phones

### ISSUE THREAD

**Issue by iceberg1369** [stephentuso/welcome-android#23]
swipeToDismiss(true) does not work if phone language set to RTL languages such as Arabic, Persian, ...
but once language changes to English swipeToDismiss(true) works as it should be.

**Comment by iceberg1369** [comment]
if (isRtl() || Build.VERSION.SDK_INT < 11)
            mParameters.mSwipeToDismiss = false;

**Comment by stephentuso** [comment]
This was on purpose, `WelcomeScreenHider` wasn't written to handle the fade animation when RTL was enabled. `SimpleViewPagerIndicator` also needed some changes. This has been fixed on the dev branch and will be present in version 1.0
