### ISSUE TITLE
Change done button's text ²

### ISSUE THREAD

**Issue by ocanhacom** [stephentuso/welcome-android#25]
First of all, congratulations for making this excellent library. I would only like to ask if you could point any sample of code where you shows how can the done button's text be changed.

I saw this answer (https://github.com/stephentuso/welcome-android/issues/10) but I didn't figured out how the .theme works, and where should I place it. Thanks!

**Comment by stephentuso** [comment]
Thanks, I'm glad it is useful to you. The styles documentation needs some improvement. The text is still changed through styles as shown in that answer, but the `theme` method has been removed in version 1.0. The theme is now set in the Android manifest, the same way you set the theme for any other activity:
```xml
<activity android:name=".MyWelcomeActivity"
    android:theme="@style/CustomWelcomeScreenTheme"/>
```

**Comment by ocanhacom** [comment]
Works like a charm! Thanks for aswering my question. If you want, you could refer this question in the other one for future user that may find themselves in the same problem.

Again, congratulations! Keep it up!
