### ISSUE TITLE
Change action button 

### ISSUE THREAD

**Issue by marva2013** [stephentuso/welcome-android#26]
How to change action of button done and exit ? thanks

**Comment by stephentuso** [comment]
What do want to change the actions to? Directly changing the actions isn't supported by the library, but it is possible if you really want to. 

Depending on what you want to do maybe the BUTTON_BAR [bottom layout](https://github.com/stephentuso/welcome-android#bottom-layouts) could work, that supports implementing the click action yourself.

Or, take a look at [results](https://github.com/stephentuso/welcome-android#results), that might be what you're looking for. 

To directly change the actions, you could override `onCreate` in your `WelcomeActivity` subclass, and the use `findViewById` to access the buttons and change their `OnClickListener`. By default they both call `completeWelcomeScreen()`. Note that this could possible break in any future update.

**Comment by marva2013** [comment]
Thanks :)
