### ISSUE TITLE
Error: Execution failed for task ':library:generatePublicXml'. > A problem occurred starting process 'command 'bash''

### ISSUE THREAD

**Issue by Gosha98** [stephentuso/welcome-android#27]
After downloading the source and put it into Android studio i got that error. 
Event Log:
13:09:40 Executing tasks: [:library:generateDebugSources, :library:generateDebugAndroidTestSources, :library:mockableAndroidJar, :library:prepareDebugUnitTestDependencies, :sample:generateDebugSources, :sample:mockableAndroidJar, :sample:prepareDebugUnitTestDependencies, :sample:generateDebugAndroidTestSources]
13:09:52 Gradle build finished with 1 error(s) in 14s 87ms

// Thank you

**Comment by stephentuso** [comment]
Oops, are you on Windows? I guess `ignoreExitValue` doesn't apply if the executable can't be found.

**Comment by stephentuso** [comment]
The latest commit on the `dev` branch should fix this, do a pull and Gradle sync, then try building again.

**Comment by Gosha98** [comment]
Thank you 😊
