### ISSUE TITLE
Binary XML file line #30: You must supply a layout_height attribute.

### ISSUE THREAD

**Issue by Ant1Zykl0n** [stephentuso/welcome-android#29]
Just by following your basic tutorial of the README.md the app is crashing when started.

Caused by: android.view.InflateException: Binary XML file line #30: Binary XML file line #30: You must supply a layout_height attribute.

Seems like inflating R.layout.wel_activity_welcome is not working. When I look at the code there is no height attribute for the View at line #30

**Comment by stephentuso** [comment]
That height is set through styles to allow it to be customized, sounds like the wrong theme is being used. Did you add `android:theme="@style/WelcomeScreenTheme"` to the tag of your WelcomeActivity in the android manifest?

**Comment by Ant1Zykl0n** [comment]
Ah, my bad =| Thank you.
