### ISSUE TITLE
Welcome Screen shows  only one time

### ISSUE THREAD

**Issue by mosi5505** [stephentuso/welcome-android#31]
Hi
at first i thank you for your good library...
i use it with the default configuration you explain at introduction page of Github...
but when i install my app in mobile i see welcome screen one time, and on another use this page is invisible...
i want to see it every time my application is started not only in first use...

best thanks...

**Comment by stephentuso** [comment]
That is the behaviour when using `.show()`, as usually onboarding/intro screens are only shown on the first app launch. You can use `.forceShow()` to always show the welcome screen. 

However, be careful, I just realized there's no protection against starting overlapping welcome screens like with `.show()` when the activity is recreated (try rotating the device). You may need to store something in the `savedInstanceState` and check that to make sure it's only started once. You might also be able to start it from an `Application` subclass instead, I can't check that at the moment though.
