### ISSUE TITLE
Hard coded strings

### ISSUE THREAD

**Issue by KowalskiOmniROM** [stephentuso/welcome-android#35]
Hello Stephen Tuso.
Thank you for your awesome App.

The "issue" i want to report, is that all displayed text on the welcome screens is hard coded

Ex: [https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/java/com/stephentuso/welcomeexample/DefaultWelcomeActivity.java](url)
```
.page(new TitlePage(R.drawable.ic_image_white, "Default Welcome Screen"))
                .page(new BasicPage(R.drawable.ic_style_white, "Default style", "No custom styles are applied to this welcome screen"))
.page(new BasicPage(R.drawable.ic_image_white, "Default properties", "No properties were set on the WelcomeScreenBuilder"))
```
So, I found how to expose these hard coded strings [https://github.com/KowalskiOmniROM/welcome-android/blob/master/sample/src/main/java/com/stephentuso/welcomeexample/DefaultWelcomeActivity.java](url)

Due of my lack of knowledge, I didn't figure how to expose:
[https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/java/com/stephentuso/welcomeexample/fragment/ExampleFragment.java](url)
`Toast.makeText(getContext(), "Button clicked in custom fragment", Toast.LENGTH_SHORT).show();`

Anyway, thank you for your great work.
Have a nice day.

**Comment by stephentuso** [comment]
In a real app, using resources for strings is the best practice, but for the purposes of the demo I'm going to leave them hard coded, unless for some reason internationalization is added at some point
