### ISSUE TITLE
Trouble saving to SharedPreferences

### ISSUE THREAD

**Issue by MagicTurtle8** [stephentuso/welcome-android#37]
I have a custom finish button which I want to save a bunch of strings to SharedPreferences before calling finish but for some reason it does not end up saving.

It'll save if I create an intent to launch another activity, however, with `new WelcomeFinisher(WelcomeFragment_2.this).finish();` nothing gets saved.

I've tried SharedPreferece editor .commit(), adding a countdowntimer and also post handler but nothing seems to work for me.

`

**Comment by stephentuso** [comment]
You're saving the strings in the `OnClickListener`? There shouldn't any conflicts with that anywhere. Make sure you're saving the strings before using the `WelcomeFinisher`.

I quickly tested it with the custom fragment in the sample ([DoneFragment](https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/java/com/stephentuso/welcomeexample/fragment/DoneFragment.java)) and it saved fine, here's the `OnClickListener`:

```java
@Override
public void onClick(View v) {
    PreferenceManager.getDefaultSharedPreferences(getActivity())
            .edit()
            .putString("test", new Date().toString())
            .apply();
    new WelcomeFinisher(DoneFragment.this).finish();
}
```

**Comment by MagicTurtle8** [comment]
Yep I saved it in the listener just like the example. I've created a fresh project and was able to successfully save through SP just like you did. 

Not sure why the original app is still behaving like so. I'll close this since I beleive the problem lies elsewhere.  Thanks for the reply
