### ISSUE TITLE
Text & Indicator Colors

### ISSUE THREAD

**Issue by cahyoarjuna** [stephentuso/welcome-android#42]
How to change text(skip) and indicator color in bottom layout? (By default just White Color) Thanks

**Comment by stephentuso** [comment]
This is done with [styles](https://github.com/stephentuso/welcome-android#styles). Look at [LightWelcomeScreenTheme](https://github.com/stephentuso/welcome-android/blob/master/sample/src/main/res/values/styles.xml#L37) in the sample styles for an example.
