### ISSUE TITLE
Cause a problen in Android O

### ISSUE THREAD

**Issue by HarborZeng** [stephentuso/welcome-android#44]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.0.0-alpha1, 25.3.1. Examples include com.android.support:animated-vector-drawable:26.0.0-alpha1 and com.android.support:preference-v7:25.3.1 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)

**Comment by HarborZeng** [comment]
@stephentuso

**Comment by stephentuso** [comment]
@HarborZeng I'll look at this later today, are you including `26.0.0-alpha1` yourself? I won't update the library to `26.x` yet because it is still a prerelease, I'll update it to `25.4.0` though.
