### ISSUE TITLE
layout_height not seted(Bug)

### ISSUE THREAD

**Issue by handinux** [stephentuso/welcome-android#46]
Hi. Thanks for great work.
When i use library iget the error Binary XML file line #30: You must supply a layout_height attribute. because of in wel_activity_welcome.xml layout_height of View not seted.

**Comment by stephentuso** [comment]
Did you set the theme correctly in the AndroidManifest? https://github.com/stephentuso/welcome-android#extend-welcomeactivity

**Comment by stephentuso** [comment]
Duplicate of #29

**Comment by handinux** [comment]
Oh.Thank you man :)
You saved me.
