### ISSUE TITLE
Configuration does not accept Color Library

### ISSUE THREAD

**Issue by brendabrandy** [stephentuso/welcome-android#5]
I was trying to write a unit test for welcome screen, and before I do that, I try to make a welcome screen with the library. I was trying to change the code in the configuration as follow:

`new WelcomeScreenBuilder(this).defaultBackgroundColor(Color.RED)`

An error popped up:"Expect Resource of type color", even though Color is an inbuilt library in android studio. Maybe we can overload the function so that the Colo library can also be accepted.

**Comment by stephentuso** [comment]
To use a color int, use the method that accepts a `BackgroundColor` like so: `defaultBackgroundColor(new BackgroundColor(Color.RED))`.
