### ISSUE TITLE
Error in overriding configuration and related color issues

### ISSUE THREAD

**Issue by brendabrandy** [stephentuso/welcome-android#6]
In the following code, I got two errors

```java

public class MyWelcomeActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_welcome);
    }


    @Override
    protected WelcomeScreenConfiguration configuration() {
        return new WelcomeScreenBuilder(this)
                .theme(R.style.WelcomeScreenTheme_Light)
                .defaultBackgroundColor(new BackgroundColor(Color.RED))
                .titlePage(R.drawable.logotest, "Title")
                .basicPage(R.drawable.photo1test, "Header", "More text.", new BackgroundColor(Color.GREEN));
                .basicPage(R.drawable.photo2test, "Lorem ipsum", "dolor sit amet.")
                .swipeToDismiss(true)
                .build();
    }
}
```
Error 1: There is no override of configuration()
Error 2: The .basicPage that has a background color was expecting an integer, but the wrapper of background color does not return such an integer. 

What can I do?
Thanks!

**Comment by stephentuso** [comment]
You need to extend `WelcomeActivity`, not `AppCompatActivity`.

There is not currently a `basicPage` method that accepts a `BackgroundColor`, only a color resource id. That may change in the future, after some refactoring is done. 

However, for Android it is good practice to put colors in a resource file (generally `colors.xml`). For the equivalent of `Color.GREEN`, you would put `<color name="green">#00ff00</color>`, and then replace the `new BackgroundColor(...)` code with `R.color.green`.

**Comment by stephentuso** [comment]
Also, it is not necessary to override `onCreate`, and setting the content view to a layout without the correct ids will cause a crash. That isn't very clear in the readme, I will fix that.
