### ISSUE TITLE
prevent "back" from closing the welcome activity

### ISSUE THREAD

**Issue by jossef** [stephentuso/welcome-android#60]
is there a way to prevent "back" from closing the welcome activity?

if not, this may be a nice optional feature.
context: I don't want the user to close the welcome screen accidentally

**Comment by 24Lathiya** [comment]
I also want to prevent back button from closing welcome activity. so i applied  
.backButtonSkips(false)
but still it is closing welcome activity.
i think this issue should be resolve ASAP.
