### ISSUE TITLE
 java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by ashkryab** [stephentuso/welcome-android#62]
``
android.app.Activity.onCreate (Activity.java:1038)
--
  | android.support.v4.app.SupportActivity.onCreate (SupportActivity.java:66)
  | android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:321)
  | android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:84)
  | com.stephentuso.welcome.WelcomeActivity.onCreate (WelcomeActivity.java:32)      <-----------
  | android.app.Activity.performCreate (Activity.java:7174)
  | android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1220)
  | android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)
  | android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  | android.app.ActivityThread.-wrap11 (Unknown Source)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  | android.os.Handler.dispatchMessage (Handler.java:105)
  | android.os.Looper.loop (Looper.java:164)
  | android.app.ActivityThread.main (ActivityThread.java:6940)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

``

in manifest 
``
<activity
            android:name=".ui.intro.IntroActivity"
            android:screenOrientation="portrait"
            android:theme="@style/WelcomeScreenTheme" />
``

Samsung Note 8, android 8.0.0

**Comment by ankursharma234** [comment]
Getting the same error for multiple devices

**Comment by VishalNehra** [comment]
+1
