### ISSUE TITLE
Testing welcome android in another project

### ISSUE THREAD

**Issue by brendabrandy** [stephentuso/welcome-android#7]
I was looking up some documentation related to android testing and it was advised that if I am testing a library, I should open a new project and test the methods. Could that be incorporated into the github repo ? If so, how?

Thanks!

**Comment by hjJunior** [comment]
`java.lang.NoSuchFieldError: No static field view_pager of type I in class Lcom/stephentuso/welcome/R$id; or its superclasses (declaration of 'com.stephentuso.welcome.R$id' appears in /data/data/com.omeuprofissional.cep/files/instant-run/dex/slice-slice_1-classes.dex)`

Error :( i tried use in my project, i receive this error on logcat

**Comment by brendabrandy** [comment]
U had the same error once actually, you need to set up an xml file with viewpager in it. I got the inspiration from the sample in the documentation.

**Comment by stephentuso** [comment]
@brendabrandy I'll go ahead and add tests to this repo soon.

@hjJunior I haven't seen that before. Do you happen to have a layout file called `activity_welcome.xml` in your app? That might be able to cause a conflict. Or, does one of the layouts in your app contain the same id (`view_pager)`? If either of those are true, try changing the name or id. In the next update I will be adding prefixes to all resources to avoid this. If that's not it, open a new issue and include some more details if possible, thanks.

**Comment by hjJunior** [comment]
@stephentuso  thanks for contact, it's solved!!! I has layout `activity_welcome`, i renamed and Perfect run :+1:

**Comment by stephentuso** [comment]
Awesome, glad that worked
