### ISSUE TITLE
how to access Done button

### ISSUE THREAD

**Issue by SahajRana** [stephentuso/welcome-android#9]
hey! this library is really great.. i have been using it lately and i need to override done button, could you help me if there is any possible solution to it. 

I tried to do it like this
`public class MyWelcomeActivity extends WelcomeActivity `
`{`
    `@Override
    protected WelcomeScreenConfiguration configuration()`

  ` {
        DoneButton done = new DoneButton(findViewById(R.id.button_done));
        done.setOnClickListener(new View.OnClickListener() {
            @Override`
            `public void onClick(View v) {
                Log.e("SahajLOG", "Done Button Called ");
                completeWelcomeScreen();
            }
        });`
        `return new WelcomeScreenBuilder(this)
                .theme(R.style.CustomWelcomeScreenTheme)
                .defaultTitleTypefacePath("Montserrat-Bold.ttf")
                .defaultHeaderTypefacePath("Montserrat-Bold.ttf")
                .titlePage(R.drawable.traffic_sign, "Welcome", R.color.SwipeScreen1)
                .page(new WelcomeFragmentHolder()
 {
                    @Override
                    protected android.support.v4.app.Fragment fragment() {
                        return new WelcomeProfileFillFragment();
                    }`
                `}, R.color.material_green)
                //.swipeToDismiss(true)
                .build();
    }`
`}`

**Comment by stephentuso** [comment]
Thanks,
What exactly do you want to change about the done button? Do you just want to change the text/style? Or do you want to use a button you've included in a custom fragment instead?

**Comment by SahajRana** [comment]
I have actually added a fragment which is like a Form Filling so, when the done button is pressed i want to check if the entered information is correct and is not empty.

**Comment by stephentuso** [comment]
That's actually the next feature I'm going to add, for now the easiest thing to do is to put a button in your fragment layout and handle the click and validation in your fragment, and call `.useCustomDoneButton(true)` on the `WelcomeScreenBuilder`. To finish the welcome screen, add the following to the end of your new click listener:

```new WelcomeScreenFinisher(WelcomeProfileFillFragment.this).finish()```

**Comment by SahajRana** [comment]
okie thanks! I will try doing this thing.
